name: branch sync
on:
  push:
    branches:
    - ng
jobs:
  prepare:
    if: vars.ENABLE_BRANCH_SYNC == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ng
        path: mcpelauncher-ng
        submodules: true
    - name: Update branches
      run: |
        set -x
        dirs=( "mcpelauncher-ng" )
        common_submodules=( "axml-parser" "file-util" "google-play-api" "mcpelauncher-apkinfo" "mcpelauncher-extract" )
        # from https://github.com/orgs/community/discussions/26560
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git -C mcpelauncher-ng/playdl-signin-ui-qt fetch origin HEAD
        git -C mcpelauncher-ng/playdl-signin-ui-qt reset --hard FETCH_HEAD
        git -C mcpelauncher-ng/mcpelauncher-ui-qt fetch origin ng
        git -C mcpelauncher-ng/mcpelauncher-ui-qt reset --hard FETCH_HEAD
        for dir in "${dirs[@]}"
        do
          pushd "$dir"
          for submodule in "${common_submodules[@]}"
          do
            git -C "$submodule" fetch origin HEAD
            git -C "$submodule" reset --hard FETCH_HEAD
          done
          git add . && git commit -m "Branch Sync" || (echo "Nothing to do" && exit 0)
          git push origin "HEAD:refs/heads/branch-sync-$dir" -f 
          echo "$dir=$(git rev-parse HEAD)" >> $GITHUB_ENV
          popd
        done
      shell: bash
    outputs:
      mcpelauncher-ng: ${{ env.mcpelauncher-ng }}
      sync: ${{ env.mcpelauncher-ng  && 'true' || 'false' }}
  deploy:
    if: needs.prepare.outputs.sync == 'true' && !failure() && !cancelled()
    needs:
    - prepare
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ng
        path: mcpelauncher-ng
    - name: Update branches
      run: |
        # from https://github.com/orgs/community/discussions/26560
        git -C mcpelauncher-ng config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git -C mcpelauncher-ng config user.name "github-actions[bot]"
        git -C mcpelauncher-ng fetch origin ${{ needs.prepare.outputs.mcpelauncher-ng }}
        git -C mcpelauncher-ng push origin ${{ needs.prepare.outputs.mcpelauncher-ng }}:ng
      shell: bash
